# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3owJZYsa1VoYm59LB1wCOGrU7m0-P67

Solicitar um numero inteiro positivo N ao usuario, imprimir os numeros de N a 1. Realizar o exercicio com loops de for e while.
"""

N = int(input("Entre com um numero inteiro maior que 1"))

print("For")
for n in range(N):
  print(f"{N-n}", end="")
print()

N = int(input("Entre com um numero inteiro maior que 1"))

print("while")
i = 0
while i < N:
   print(f"{N-i}", end="")
   i += 1

N = int(input("Entre com um numero positivo maior que 1"))

print("For")
mult = -1
fat = 1

for n in range(N):
  num = fat * (N-n)
  fat *= mult
  print(f"{num}", end=" ")
print()

N = int(input("Entre com um numero positivo maior que 1"))

print("while")
mult = -1
fat = 1
i = 0
while i < N:
  num = fat * (N-i)
  fat *= mult
  print(f"{num}", end=" ")
  i += 1

"""O codigo abaixo percorre uma lista de palavras via while. Reproduza-o com uso de for."""

N = int(input("Entre com numero inteiro maior que 1" ))
print("For: ")
for i in range(1,N):
  print(f"{i*i}")

N = int(input("Entre com numero inteiro maior que 1" ))
print("while ")
i = 1
while i < n:
  print(f"{i*i}")
  i += 1

"""Solicitar uma palavra ao usuario e dizer se a palavra e um palindromo, isto e, pode ser lida igualmente da esquerda para a direita e vice-versa. Exemplos de palavras que sao palindromos: ovo, radar, mirim, reviver."""

palavra = str(input('Digite uma palavra: ')).strip().lower()
invertida  = palavra[::-1]
if palavra == invertida:
  print(f'A palavra {palavra} e palindromo')
else:
   print(f'A palavra {palavra} nao e palindromo')

"""fazer um programa que solicita um numero inteiro positivo N ao usuario e imprime o seguinte padrao na tela."""

for x in range(999):
  X = int(input("Digite um numero inteiro: "))
  if X == 1:
   print("\n -\n| |\n -")
  elif X == 2:
    print("\n --\n|  |\n|  |\n --")
  elif X == 5:
    print("\n -----\n|     |\n|     |\n|     |\n|     |\n|     |\n -----")
  elif X == 0:
    break
  else:
    print("Digite outro valor")

"""fazer um programa que solicita um numero inteiro positivo N ao usuario e imprime o seguinte padraona tela."""

for x in range(999):
  X = int(input("Digite um numero inteiro: "))
  if X == 5:
   print("\n+\n++\n+++\n++++\n+++++")
  elif X == 0:
    break
  else:
    print("Digite outro valor")

numero = int(input('Digite um numero: '))
print(' ', end='')
print('-'*numero)
for vezes in range(numero):
  print('|', end='')
  print(' '*numero, end='')
  print('|')

print(' ', end='')
print('-'*numero)

numero = int(input('Digite um numero intero: '))
print('+'*numero)